"""Personalized recommendations built from a user's real activity.

OMDb only supports title search (`s=`) and id lookup (`i=`) — there is no
genre-browse or "similar movies" endpoint. So recommendations are generated by
re-searching OMDb with the user's own search-history keywords and recently-viewed
titles, then deduped, filtered, scored and reason-tagged. Genre preferences rank
and explain results rather than drive OMDb discovery (which isn't possible).
"""
from sqlalchemy.orm import Session

from app.services import (
    history_service,
    omdb_service,
    preference_service,
    recently_viewed_service,
)

MAX_RECOMMENDATIONS = 10
MAX_SEEDS = 5  # bound the number of OMDb calls per request


def _poster(p: str | None) -> str | None:
    return p if p and p != "N/A" else None


def generate(db: Session, user_id: str) -> list[dict]:
    viewed = recently_viewed_service.viewed_imdb_ids(db, user_id)
    top_genres = preference_service.top_genres(db, user_id, limit=3)

    # Seeds in priority order: recent searches, then recently-viewed titles.
    seeds: list[tuple[str, str, int]] = []  # (keyword, reason, base_score)
    for kw in history_service.recent_keywords(db, user_id, limit=3):
        seeds.append((kw, "Based on your recent searches", 90))
    for title in recently_viewed_service.recent_titles(db, user_id, limit=3):
        seeds.append((title, "Similar to movies you viewed", 82))
    seeds = seeds[:MAX_SEEDS]

    recs: list[dict] = []
    seen: set[str] = set()
    for keyword, reason, base in seeds:
        try:
            results = omdb_service.search_movies(keyword, 1)["results"]
        except Exception:
            continue
        for i, item in enumerate(results):
            imdb_id = item.get("imdbID")
            # Skip dupes and movies the user has already viewed (keep recs fresh).
            if not imdb_id or imdb_id in seen or imdb_id in viewed:
                continue
            seen.add(imdb_id)
            recs.append(
                {
                    "imdb_id": imdb_id,
                    "title": item.get("Title", ""),
                    "genre": top_genres[0] if top_genres else None,
                    "poster": _poster(item.get("Poster")),
                    "reason": reason,
                    "score": max(50, base - i * 2),
                }
            )

    recs.sort(key=lambda r: r["score"], reverse=True)
    return recs[:MAX_RECOMMENDATIONS]
