"""add otp channel support

Revision ID: 0069bda61840
Revises: 7fdb853319ec
Create Date: 2026-06-02 18:17:12.631313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0069bda61840'
down_revision: Union[str, Sequence[str], None] = '7fdb853319ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'channel',
               existing_type=mysql.ENUM('EMAIL', 'PHONE'),
               type_=sa.Enum('EMAIL', 'SMS', name='otpchannel'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'channel',
               existing_type=sa.Enum('EMAIL', 'SMS', name='otpchannel'),
               type_=mysql.ENUM('EMAIL', 'PHONE'),
               existing_nullable=False)
    # ### end Alembic commands ###
