"""add otp channel

Revision ID: 13dca6926197
Revises: 27be295b3cf4
Create Date: 2026-06-05 15:28:44.072343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dca6926197'
down_revision: Union[str, Sequence[str], None] = '27be295b3cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='otpchannel'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'channel')
    # ### end Alembic commands ###
