"""Corses table

Revision ID: 15f408830404
Revises: fdd242c6f8cc
Create Date: 2026-07-01 11:57:23.020973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f408830404'
down_revision: Union[str, Sequence[str], None] = 'fdd242c6f8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('instructor_teacher_profile_id', sa.String(length=36), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='coursedifficulty'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'UNPUBLISHED', name='coursestatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_courses_created_by')),
    sa.ForeignKeyConstraint(['instructor_teacher_profile_id'], ['teacher_profiles.id'], name=op.f('fk_courses_instructor_teacher_profile_id')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_courses_subject_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_table('course_modules',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_modules_course_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_modules'))
    )
    op.create_table('course_visibility',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('visibility_type', sa.Enum('ALL_STUDENTS', 'ASSIGNED_ONLY', 'GROUP', name='coursevisibilitytype'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_visibility_course_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_visibility')),
    sa.UniqueConstraint('course_id', name=op.f('uq_course_visibility_course_id'))
    )
    op.create_table('student_course_assignments',
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_student_course_assignments_assigned_by')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_student_course_assignments_course_id')),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_student_course_assignments_student_profile_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_course_assignments')),
    sa.UniqueConstraint('student_profile_id', 'course_id', name='uq_student_course_assignment')
    )
    op.create_table('lessons',
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_title', sa.String(length=255), nullable=False),
    sa.Column('lesson_description', sa.Text(), nullable=True),
    sa.Column('lesson_type', sa.Enum('VIDEO', 'PDF', 'TEXT', name='lessontype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name=op.f('fk_lessons_module_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_table('course_progress',
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('completed_lessons', sa.Integer(), nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('last_accessed_lesson_id', sa.String(length=36), nullable=True),
    sa.Column('next_lesson_id', sa.String(length=36), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_progress_course_id')),
    sa.ForeignKeyConstraint(['last_accessed_lesson_id'], ['lessons.id'], name=op.f('fk_course_progress_last_accessed_lesson_id')),
    sa.ForeignKeyConstraint(['next_lesson_id'], ['lessons.id'], name=op.f('fk_course_progress_next_lesson_id')),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_course_progress_student_profile_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_progress')),
    sa.UniqueConstraint('student_profile_id', 'course_id', name='uq_student_course_progress')
    )
    op.create_table('lesson_contents',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('content_url', sa.String(length=1000), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_contents_lesson_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_contents'))
    )
    op.create_table('lesson_progress',
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('watch_percentage', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_progress_lesson_id')),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_lesson_progress_student_profile_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_progress')),
    sa.UniqueConstraint('student_profile_id', 'lesson_id', name='uq_student_lesson_progress')
    )
    op.add_column('users', sa.Column('reference_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reference_phone_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_reference_email'), 'users', ['reference_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reference_email'), table_name='users')
    op.drop_column('users', 'reference_phone_number')
    op.drop_column('users', 'reference_email')
    op.drop_table('lesson_progress')
    op.drop_table('lesson_contents')
    op.drop_table('course_progress')
    op.drop_table('lessons')
    op.drop_table('student_course_assignments')
    op.drop_table('course_visibility')
    op.drop_table('course_modules')
    op.drop_table('courses')
    # ### end Alembic commands ###
