"""agree_to_terms field added in user table

Revision ID: 21742d0e807b
Revises: 27be295b3cf4
Create Date: 2026-06-05 11:49:30.293266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21742d0e807b'
down_revision: Union[str, Sequence[str], None] = '27be295b3cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agree_to_terms', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agree_to_terms')
    # ### end Alembic commands ###
