"""Creating country table

Revision ID: 30367e16181a
Revises: 12490eab187c
Create Date: 2026-05-29 18:33:31.899660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30367e16181a'
down_revision: Union[str, Sequence[str], None] = '12490eab187c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('phone_code', sa.String(length=10), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    op.add_column('users', sa.Column('country_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index('ix_user_country_phone', 'users', ['country_id', 'phone_number'], unique=False)
    op.create_index(op.f('ix_users_country_id'), 'users', ['country_id'], unique=False)
    op.create_unique_constraint('uq_user_country_phone', 'users', ['country_id', 'phone_number'])
    op.create_foreign_key(op.f('fk_users_country_id'), 'users', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_country_id'), 'users', type_='foreignkey')
    op.drop_constraint('uq_user_country_phone', 'users', type_='unique')
    op.drop_index(op.f('ix_users_country_id'), table_name='users')
    op.drop_index('ix_user_country_phone', table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'country_id')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
