"""Modifications in lessons table

Revision ID: 52c4f110980a
Revises: d6cb68cd5c75
Create Date: 2026-07-03 17:01:08.765436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52c4f110980a'
down_revision: Union[str, Sequence[str], None] = 'd6cb68cd5c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
