"""add channel to otp_verifications

Revision ID: 7fdb853319ec
Revises: 11b05d36430f
Create Date: 2026-06-02 17:32:02.278562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdb853319ec'
down_revision: Union[str, Sequence[str], None] = '11b05d36430f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('channel', sa.Enum('EMAIL', 'PHONE', name='otpchannel'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'channel')
    # ### end Alembic commands ###
