"""add learning fields to student profile

Revision ID: 94f6f6aebc39
Revises: e0778f955062
Create Date: 2026-06-11 12:04:33.803044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f6f6aebc39'
down_revision: Union[str, Sequence[str], None] = 'e0778f955062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('learning_interests', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_learning_style', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'preferred_learning_style')
    op.drop_column('student_profiles', 'learning_interests')
    # ### end Alembic commands ###
