"""added imports

Revision ID: b0732e264f4f
Revises: 7d14e3c0328b
Create Date: 2026-06-18 15:49:14.998014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0732e264f4f'
down_revision: Union[str, Sequence[str], None] = '7d14e3c0328b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('name', name=op.f('uq_subjects_name'))
    )
    op.create_table('teacher_subjects',
    sa.Column('teacher_profile_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teacher_subjects_subject_id')),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], name=op.f('fk_teacher_subjects_teacher_profile_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_subjects')),
    sa.UniqueConstraint('teacher_profile_id', 'subject_id', name='uq_teacher_subject')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
