"""Foreign key reference added for user id in roles table.

Revision ID: b404682c2a85
Revises: e0b540a131ee
Create Date: 2026-06-12 17:44:17.481304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b404682c2a85'
down_revision: Union[str, Sequence[str], None] = 'e0b540a131ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
