"""Removed some fields in parentChildren model

Revision ID: c87fba0ddb52
Revises: b404682c2a85
Create Date: 2026-06-18 13:35:53.885522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c87fba0ddb52'
down_revision: Union[str, Sequence[str], None] = 'b404682c2a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_children', 'child_name')
    op.drop_column('parent_children', 'school_name')
    op.drop_column('parent_children', 'grade')
    op.drop_index(op.f('uq_student_profiles_user_id'), table_name='student_profiles')
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.alter_column('teacher_profiles', 'years_of_experience',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_profiles', 'years_of_experience',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.create_index(op.f('uq_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.add_column('parent_children', sa.Column('grade', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('parent_children', sa.Column('school_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('parent_children', sa.Column('child_name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
