"""added stu_ref_id in parent profile

Revision ID: da71966abf03
Revises: b0732e264f4f
Create Date: 2026-06-18 16:14:14.701794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da71966abf03'
down_revision: Union[str, Sequence[str], None] = 'b0732e264f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_profiles', sa.Column('student_reference_id', sa.String(length=255), nullable=True))
    op.drop_column('parent_profiles', 'relationship_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_profiles', sa.Column('relationship_type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('parent_profiles', 'student_reference_id')
    # ### end Alembic commands ###
