"""recreate parent_children

Revision ID: df1dd0787997
Revises: 230f384251dd
Create Date: 2026-06-19 13:02:17.235387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1dd0787997'
down_revision: Union[str, Sequence[str], None] = '230f384251dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_children',
    sa.Column('parent_profile_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_profile_id'], ['parent_profiles.id'], name=op.f('fk_parent_children_parent_profile_id')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_parent_children_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_children'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_children')
    # ### end Alembic commands ###
