"""user model scurity question can be null

Revision ID: ec406916067f
Revises: e4619c6a6069
Create Date: 2026-06-24 13:27:03.877412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec406916067f'
down_revision: Union[str, Sequence[str], None] = 'e4619c6a6069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'security_question',
               existing_type=mysql.ENUM('FAVORITE_FOOD', 'FAVORITE_COUNTRY', 'FAVORITE_SPORT'),
               nullable=True)
    op.alter_column('users', 'security_answer_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'security_answer_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'security_question',
               existing_type=mysql.ENUM('FAVORITE_FOOD', 'FAVORITE_COUNTRY', 'FAVORITE_SPORT'),
               nullable=False)
    # ### end Alembic commands ###
